# https://docs.microsoft.com/ja-jp/dotnet/devops/dotnet-test-github-action

name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.301' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test(AVX2)
      run: dotnet test --configuration Release --no-restore --verbosity normal
      env:
        COMPlus_EnableAVX2: 1
        COMPlus_EnableSSE41: 1
        COMPlus_EnableSSSE3: 1
        COMPlus_EnableSSE2: 1
    
    - name: Test(SSE41)
      run: dotnet test --configuration Release --no-restore --verbosity normal
      env:
        COMPlus_EnableAVX2: 0
        COMPlus_EnableSSE41: 1
        COMPlus_EnableSSSE3: 1
        COMPlus_EnableSSE2: 1

    - name: Test(SSSE3)
      run: dotnet test --configuration Release --no-restore --verbosity normal
      env:
        COMPlus_EnableAVX2: 0
        COMPlus_EnableSSE41: 0
        COMPlus_EnableSSSE3: 1
        COMPlus_EnableSSE2: 1

    - name: Test(SSE2)
      run: dotnet test --configuration Release --no-restore --verbosity normal
      env:
        COMPlus_EnableAVX2: 0
        COMPlus_EnableSSE41: 0
        COMPlus_EnableSSSE3: 0
        COMPlus_EnableSSE2: 1

    - name: Test(NoSSE)
      run: dotnet test --configuration Release --no-restore --verbosity normal
      env:
        COMPlus_EnableAVX2: 0
        COMPlus_EnableSSE41: 0
        COMPlus_EnableSSSE3: 0
        COMPlus_EnableSSE2: 0